# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f77d01155512861e56b14dc510489ac1d80be5b85393f5c8b151a720a767aac7224d30067008841679be35c5834324966942fd063d6488b6e2553daaeb15a56

test:
  secret_key_base: 605346d4d210d2bb65c48fd21c10bcbd6d80ce67d67df0c35575f6e2a446c7f92e44a276058ec0b1b4e3c97027ab461f311d4cc984fec93983fda0ed4578191f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
